In [3]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
a=np.ones(10)

In [6]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
a+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
a=np.arange(10,51)

In [11]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [14]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [18]:
a=np.arange(0,9)

In [19]:
a.shape

(9,)

In [20]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
a.shape=3,3

In [22]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.random.rand()

0.508318664507347

In [48]:
np.random.randn(1,25)

array([[-0.6906285 ,  0.31821928, -0.74527339, -0.8361176 ,  0.87402362,
        -1.09070958, -1.53050595,  1.36708358,  0.11922463,  2.88393856,
        -0.73715682,  0.20792107,  0.85460271,  0.56692378,  0.15359742,
         0.59310875, -0.22817315, -0.16232015,  1.14232968,  0.95158309,
        -1.03028157, -1.04777153,  1.10945051, -0.37301638, -1.0666511 ]])

In [77]:
np.arange(0,1.01,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [47]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [4]:
a=np.arange(1,26).reshape(5,5)

In [178]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [179]:
a[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [80]:
a[3,4]

20

In [187]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [97]:
a[4,0:5]

array([21, 22, 23, 24, 25])

In [98]:
a[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [172]:
a=np.arange(1,26)

In [171]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [118]:
a.sum()

325

In [156]:
a.std()

7.211102550927978

In [9]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])