In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
dataset=pd.read_csv(r'C:\Users\USER\Downloads\tips.csv')

In [45]:
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [46]:
x=dataset.iloc[:,:-1].values

In [47]:
x

array([[16.99, 1.01, 'Female', 'No', 'Sun', 'Dinner'],
       [10.34, 1.66, 'Male', 'No', 'Sun', 'Dinner'],
       [21.01, 3.5, 'Male', 'No', 'Sun', 'Dinner'],
       ...,
       [22.67, 2.0, 'Male', 'Yes', 'Sat', 'Dinner'],
       [17.82, 1.75, 'Male', 'No', 'Sat', 'Dinner'],
       [18.78, 3.0, 'Female', 'No', 'Thur', 'Dinner']], dtype=object)

In [48]:
y=dataset.iloc[:,-1].values

In [49]:
y

array([2, 3, 3, 2, 4, 4, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 3, 3, 3, 3, 2, 2,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 4, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2,
       4, 2, 2, 4, 3, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 4, 2, 2, 2, 4, 3, 3,
       2, 1, 2, 2, 2, 3, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 1, 2, 2, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 3, 2, 3, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 6, 2, 2, 2, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 5, 6, 2, 2, 3, 2, 2, 2, 2, 2, 3, 4,
       4, 5, 6, 4, 2, 4, 4, 2, 3, 2, 2, 3, 2, 4, 2, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 4, 2, 3, 4, 2, 5, 3, 5, 3, 3, 2, 2, 2, 2, 2, 2, 2, 4,
       2, 2, 3, 2, 2, 2, 4, 3, 3, 4, 2, 2, 3, 4, 4, 2, 3, 2, 5, 2, 2, 4,
       2, 2, 1, 3, 2, 2, 2, 4, 2, 2, 4, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2,
       2, 2], dtype=int64)

In [50]:
sex=pd.get_dummies(dataset['sex'],drop_first=True)
smoker=pd.get_dummies(dataset['smoker'],drop_first=True)
day=pd.get_dummies(dataset['day'],drop_first=True)
time=pd.get_dummies(dataset['time'],drop_first=True)

In [51]:
sex

Male
0    False
1     True
2     True
3     True
4    False
..     ...
239   True
240  False
241   True
242   True
243  False

[244 rows x 1 columns]

In [52]:
smoker

Yes
0    False
1    False
2    False
3    False
4    False
..     ...
239  False
240   True
241   True
242  False
243  False

[244 rows x 1 columns]

In [53]:
day

Sat    Sun   Thur
0    False   True  False
1    False   True  False
2    False   True  False
3    False   True  False
4    False   True  False
..     ...    ...    ...
239   True  False  False
240   True  False  False
241   True  False  False
242   True  False  False
243  False  False   True

[244 rows x 3 columns]

In [54]:
time

Lunch
0    False
1    False
2    False
3    False
4    False
..     ...
239  False
240  False
241  False
242  False
243  False

[244 rows x 1 columns]

In [55]:
dataset.drop(['sex','smoker','day','time'],axis=1,inplace=True)

In [56]:
dataset=pd.concat([sex,smoker,day,time],axis=1)

In [57]:
dataset

Male    Yes    Sat    Sun   Thur  Lunch
0    False  False  False   True  False  False
1     True  False  False   True  False  False
2     True  False  False   True  False  False
3     True  False  False   True  False  False
4    False  False  False   True  False  False
..     ...    ...    ...    ...    ...    ...
239   True  False   True  False  False  False
240  False   True   True  False  False  False
241   True   True   True  False  False  False
242   True  False   True  False  False  False
243  False  False  False  False   True  False

[244 rows x 6 columns]

In [58]:
x=dataset.iloc[:,:-1].values

In [59]:
x

array([[False, False, False,  True, False],
       [ True, False, False,  True, False],
       [ True, False, False,  True, False],
       ...,
       [ True,  True,  True, False, False],
       [ True, False,  True, False, False],
       [False, False, False, False,  True]])

In [60]:
y=dataset.iloc[:,-1].values

In [61]:
y

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [63]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [64]:
y_pred=regressor.predict(x_test)

In [65]:
y_pred

array([-0.01227407, -0.00192375, -0.00852445,  0.01377857,  0.17026303,
        0.17026303, -0.00192375,  0.00182586,  0.0278785 ,  0.00182586,
        0.02412889, -0.00192375, -0.00852445,  1.02179108,  0.14421039,
       -0.00852445,  1.01144077, -0.01227407,  1.01144077,  0.00182586,
       -0.00192375,  0.01377857,  0.99573844, -0.00852445,  0.99573844,
        1.02179108,  0.14421039,  1.01144077, -0.00852445,  0.01377857,
        0.01377857,  1.01144077, -0.00852445,  0.02412889, -0.00852445,
        0.01752819,  0.01377857,  1.01144077, -0.01227407,  0.15991272,
        0.14421039,  1.01144077, -0.00192375,  0.01752819,  0.02412889,
        0.01752819, -0.01227407, -0.00852445,  0.01377857])

In [66]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[-0.01  0.  ]
 [-0.    0.  ]
 [-0.01  0.  ]
 [ 0.01  0.  ]
 [ 0.17  1.  ]
 [ 0.17  0.  ]
 [-0.    0.  ]
 [ 0.    0.  ]
 [ 0.03  0.  ]
 [ 0.    0.  ]
 [ 0.02  0.  ]
 [-0.    0.  ]
 [-0.01  0.  ]
 [ 1.02  1.  ]
 [ 0.14  1.  ]
 [-0.01  0.  ]
 [ 1.01  1.  ]
 [-0.01  0.  ]
 [ 1.01  0.  ]
 [ 0.    0.  ]
 [-0.    0.  ]
 [ 0.01  0.  ]
 [ 1.    1.  ]
 [-0.01  0.  ]
 [ 1.    1.  ]
 [ 1.02  1.  ]
 [ 0.14  1.  ]
 [ 1.01  1.  ]
 [-0.01  0.  ]
 [ 0.01  0.  ]
 [ 0.01  0.  ]
 [ 1.01  1.  ]
 [-0.01  0.  ]
 [ 0.02  0.  ]
 [-0.01  0.  ]
 [ 0.02  0.  ]
 [ 0.01  0.  ]
 [ 1.01  1.  ]
 [-0.01  0.  ]
 [ 0.16  1.  ]
 [ 0.14  1.  ]
 [ 1.01  1.  ]
 [-0.    0.  ]
 [ 0.02  0.  ]
 [ 0.02  0.  ]
 [ 0.02  0.  ]
 [-0.01  0.  ]
 [-0.01  0.  ]
 [ 0.01  0.  ]]
